spring:
  application:
    name: bank-account-app-test
  datasource:
    url: jdbc:h2:mem:bank-account-app-test-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true

logging:
  level:
    com.example.bank_account_app: DEBUG

bank-account-app:
  currency-exchange:
    endpoint: "https://open.er-api.com/v6/latest/"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
