spring:
  application:
    name: bank-account-app
  datasource:
    url: jdbc:h2:mem:bank-account-app-db # TODO: MLe: Can also try jdbc:h2:file:./bank-account-app-db
    username: username
    password: password123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
logging:
  level:
    com.example.bank_account_app: DEBUG

bank-account-app:
  currency-exchange:
    endpoint: "https://open.er-api.com/v6/latest/"

springdoc:
  swagger-ui:
    path: /swagger-ui.html # TODO: MLe: Remove later: http://localhost:8080/swagger-ui/index.html